### ISSUE TITLE
README 请求

### ISSUE THREAD

**Issue by weierz** [PoBlue/auto-review#2]
找个时间优化下 README？

比如：
- [x] Requirement
- [x] How to run
- [x] How does it work
- [ ] How to contribute

P.S. 我下期也要开始深度学习了。

**Comment by PoBlue** [comment]
好啊，明天完善了 ReadMe 。正式开车！

**Comment by PoBlue** [comment]
如何贡献和合作的具体事项，我争取在下个星期完成
